### ISSUE TITLE
Rendering issue - ImportError

### ISSUE THREAD

**Issue by ashok-arora** [kevslinger/DTQN#11]
Hey Kevin, 

In `DiscreteCarFlag-v0` env for `gym==0.18.0`, running it with the `--render` flag returns the traceback: 

```bash
Loading using gym.make
Traceback (most recent call last):
  File "run.py", line 333, in <module>
    run_experiment(parser.parse_args())
  File "run.py", line 21, in run_experiment
    env = env_processing.make_env(args.env)
  File "/home/hp/Desktop/ashok/DTQN-paper/utils/env_processing.py", line 46, in make_env
    env = gym.make(id_or_path)
  File "/home/hp/miniconda3/envs/dtqn/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/hp/miniconda3/envs/dtqn/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/hp/miniconda3/envs/dtqn/lib/python3.8/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/hp/miniconda3/envs/dtqn/lib/python3.8/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/home/hp/miniconda3/envs/dtqn/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hp/Desktop/ashok/DTQN-paper/envs/car_flag.py", line 12, in <module>
    from gym.utils import pyglet_rendering as visualize
ImportError: cannot import name 'pyglet_rendering' from 'gym.utils' (/home/hp/miniconda3/envs/dtqn/lib/python3.8/site-packages/gym/utils/__init__.py)
```

The solution is to replace 
```python
from gym.utils import pyglet_rendering as visualize
```
with: 
```python
from gym.envs.classic_control import rendering as visualize
```

**Comment by kevslinger** [comment]
Hi Ashok, thank you for pointing this out! I have updated the `paper` and `main` branches with your fix :+1:
