### ISSUE TITLE
Error run.py 

### ISSUE THREAD

**Issue by jewookwak** [kevslinger/DTQN#6]
(DTQN) mds@mds:~/DTQN$ python -u "/home/mds/DTQN/run.py"
Loading using gym.make
Environment with id D not found.
Loading using YAML
Traceback (most recent call last):
  File "/home/mds/DTQN/utils/env_processing.py", line 34, in make_env
    env = gym.make(id_or_path)
  File "/home/mds/anaconda3/envs/DTQN/lib/python3.8/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/home/mds/anaconda3/envs/DTQN/lib/python3.8/site-packages/gym/envs/registration.py", line 86, in make
    spec = self.spec(path)
  File "/home/mds/anaconda3/envs/DTQN/lib/python3.8/site-packages/gym/envs/registration.py", line 115, in spec
    raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))
gym.error.Error: Attempted to look up malformed environment ID: b'D'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mds/DTQN/run.py", line 533, in <module>
    run_experiment(get_args())
  File "/home/mds/DTQN/run.py", line 415, in run_experiment
    envs.append(env_processing.make_env(env_str))
  File "/home/mds/DTQN/utils/env_processing.py", line 39, in make_env
    inner_env = factory_env_from_yaml(
  File "/home/mds/anaconda3/envs/DTQN/lib/python3.8/site-packages/gym_gridverse/envs/yaml/factory.py", line 243, in factory_env_from_yaml
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mds/DTQN/envs/gridverse/D'

When I executed run.py , got above Error. I think I installed right. But might installed in wrong path. I don't understand envs/gridverse/D.
Please help me execute run.py

**Comment by kevslinger** [comment]
Hi! Thank you for your interest in DTQN! For the most stable version of the repo, please use the `paper` branch. The `main` branch is currently set up for multi-env training and so assumes you will specify 2+ environments

**Comment by jewookwak** [comment]
Thank you for reply :)
I succeed to execute run.py by changing to proper cuda, cudnn, pytorch version.
and change some of requirements' version.
